app.config(function ($translateProvider) {
    $translateProvider.translations('en', {
        LOGIN_TITLE: 'Login',
        LOGIN_USERNAME: 'User Name',
        LOGIN_PASSWORD: 'Password',
        CONTINUE: 'Continue',
        SIGIN: 'Sign in',
        CANCEL: 'Cancel',
        CONTINUE: 'Continue',
        SEARCH: 'Search',
        PAYMENT: 'Payment',

        KYAT: 'MMK',
        ACCOUNTNO: 'Account No',

        ENGLISH: 'English',
        MYANMAR: 'ျမန္မာ',
        LOGOUT: 'Logout',
        TRANSFER: 'Transfer Money',
        UTILITY: 'Utility Payment',
        TOPUP: 'Topup',
        VIEWMINI: 'View Ministatement',
        TRANHISTORY: 'Transaction History',
        PWDCHANGE: 'Password Change',
        BENEFICIARY: 'Beneficiary',
        PROFILE: 'User Profile',
        REMITTANCE: 'Remittance',

        SIDE_TITLE: 'Online banking',
        SIDE_FIRSTTEXT: 'online banking facilities offered by various financial institutions have many features and capabilities in common, but also have some that are application specific. the common features fall broadly into several categories',
        SIDE_SECONDTEXT: 'This section does not cite any references or sources. Please help improve this section by adding citations to reliable sources. Unsourced material may be challenged and removed. ',

        BALENQ_DESP: 'You can choose any account for making payment.',
        BALENQ_AVAILABLEBAL: 'Avalilable Balance',
        BALENQ_LEDGERBAL: 'Ledger Balance',

        PROFILE_FULLNAME: 'Full Name',
        PROFILE_EMAIL: 'EMAIL',

        CARD_INFO: 'Card Info:',
        TOPUP_OPERATOR: 'Mobile Operator',
        TOPUP_PHONELINE: 'Phone Line',
        TOPUP_CARDTYPE: 'Card Type',
        TOPUP_REFERENCE: 'Reference',
        TOPUP_QUANTITY: 'Topup Quantity',
        TOPUP_TRANFEES: 'Transaction Fees',
        TOPUP_NETAMT: 'Net Amount',
        TOPUP_DISCOUNTAMT: 'Discount Amount',
        // topup confirm
        TOPUP_COPERATOR: 'Mobile Operator',
        TOPUP_CPHONELINE: 'Phone Line',
        TOPUP_CCARDTYPE: 'Card Type',
        TOPUP_CQUANTITY: 'Topup Quantity',
        // topup value
        TOPUP_VALUENO: 'Your topup number is',
        TOPUP_EXPDATE: 'Expire Date is',
        TOPUP_VALUENO1: ' ',
        TOPUP_EXPDATE1: ' ',

        TRANSFER_TOACCCOUNT: 'To Account',
        TRANSFER_TRANSFERBALANCE: 'Transfer Balance',
        TRANSFER_SERVICECHARGES: 'Service Charges',
        TRANSFER_TOTALBALANCE: 'Total Balance',
        TRANSFER_REFERENCE: 'Reference',
        TRANSFER_CONTINUE: 'Continue',
        TRANSFER_BENEFICIARYNAME: 'Beneficiary Name',
        TRANSFER_ADDBENEFI: 'Add Beneficiary',
        // transfer confirm
        TRANSFER_CTOACCCOUNT: 'To Account',
        TRANSFER_CTRANSFERBALANCE: 'Transfer Balance',
        BENEFICIARY_TITLE: 'Transfer Beneficiary',
        ADDBENE_ADDBENE: 'Add Transfer Beneficiary',
        TRANSFER_TERMSANDCONS:'I agree that I have checked and verified the above information.',


        //apk
        BENEFICIARYEDIT_TITLE: 'Editing Beneficiary',
        BENEEDIT_DESP: 'You can edit beneficiary information here.',

        UTILITY_SERVICETYPE: 'Service Type',
        UTILITY_CITY: 'City',
        UTILITY_TOWNSHIP: 'Township',
        UTILITY_SERVICENO: 'Service No',
        UTILITY_BILLMONTH: 'Bill Month',
        UTILITY_REFERENCE: 'Reference',
        // utility confirm
        UTILITY_CSERVICETYPE: 'Service Type',
        UTILITY_CCITY: 'City',
        UTILITY_CTOWNSHIP: 'Township',
        UTILITY_CSERVICENO: 'Service No',
        UTILITY_BillAMOUNT: 'Bill Amount',
        UTILITY_STATUS: 'Status',
        UTILITY_BALANCE: 'Balance',
        UTILITY_DUEDATE: 'Due Date',

        BENE_DESP: 'You can remove or add new beneficiary from here.',
        BENE_ADDNEW: 'Add New',
        BENE_REMOVE: 'Remove',
        ADDBENE_ACCNO: 'Account Number',
        ADDBENE_NICKNAME: 'Nick Name',
        ADDBENE_REMARK: 'Remark',

        VIEWMINI_FROMDATE: 'From Date',
        VIEWMINI_TODATE: 'To Date',
        VIEWMINI_NOTE: 'Note : Within 1 Month Transactions Only',
        VIEWMINI_DATE: 'Date',
        VIEWMINI_CODE: 'Code',
        VIEWMINI_DEPOSIT: 'Deposit',
        VIEWMINI_WITHDRAW: 'Withdraw',
        VIEWMINI_TOTALAMT: 'Balance',
        VIEWMINI_NARRATION: 'Narration',

        CHKMYTRAN_TRANTYPE: 'Transaction Type',
        CHKMYTRAN_BILLTYPE: 'Bill Type',
        CHKMYTRAN_TOACCNO: 'Credit Account No',
        CHKMYTRAN_FROMDATE: 'From Date',
        CHKMYTRAN_TODATE: 'To Date',
        CHKMYTRAN_NOTE: 'Note : Within 1 Month Transactions Only',

        CHKMYTRAN_TRANSFERVIEW_DATE: 'Date',
        CHKMYTRAN_TRANSFERVIEW_TRANID: 'Transaction ID',
        CHKMYTRAN_TRANSFERVIEW_TRANCODE: 'Tran Code',
        CHKMYTRAN_TRANSFERVIEW_ACCNO: 'Account No',
        CHKMYTRAN_TRANSFERVIEW_AMOUNT: 'Amount',
        CHKMYTRAN_TRANSFERVIEW_REFERENCE: 'Reference',

        CHKMYTRAN_TOPUPVIEW_DATE: 'Date',
        CHKMYTRAN_TOPUPVIEW_TRANID: 'Transaction ID',
        CHKMYTRAN_TOPUPVIEW_OPERATOR: 'Operator',
        CHKMYTRAN_TOPUPVIEW_LINE: 'Line',
        CHKMYTRAN_TOPUPVIEW_CARD: 'Card',
        CHKMYTRAN_TOPUPVIEW_AMOUNT: 'Amount',
        CHKMYTRAN_TOPUPVIEW_VALUE: 'Card No',
        CHKMYTRAN_TOPUPVIEW_EXPDATE: 'Exp: Date',
        CHKMYTRAN_TOPUPVIEW_REFERENCE: 'Reference',

        CHKMYTRAN_UTILITYVIEW_DATE: 'Date',
        CHKMYTRAN_UTILITYVIEW_TRANID: 'Transaction ID',
        CHKMYTRAN_UTILITYVIEW_SERVICENO: 'Service No',
        CHKMYTRAN_UTILITYVIEW_BILLAMOUNT: 'Bill Amount',
        CHKMYTRAN_UTILITYVIEW_STATUS: 'Status',

        CHKMYTRAN_REMITTANCEVIEW_DATE: 'Date',
        CHKMYTRAN_REMITTANCEVIEW_CREDITUSER: 'Credit User',
        CHKMYTRAN_REMITTANCEVIEW_AMOUNT: 'Amount',
        CHKMYTRAN_REMITTANCEVIEW_TELEX: 'Telex',
        CHKMYTRAN_REMITTANCEVIEW_COMMISSION: 'Commission',
        CHKMYTRAN_REMITTANCEVIEW_TOTALAMOUNT: 'Total Amount',

        PWDCHANGE_FILLOLDPWD: 'Old Password',
        PWDCHANGE_FILLNEWPWD: 'New Password',
        PWDCHANGE_CURPWD: 'Current password',
        PWDCHANGE_NEWPWD: 'New password',
        PWDCHANGE_RETYPEPWD: 'Retype new assword',

        //REMITTANCE
        REMIT_NAME: 'Name',
        REMIT_BANKTYPE: 'Bank Type',
        REMIT_SELECTBANK: 'Bank Name',
        REMIT_BANK: 'Branch',
        REMIT_CITY: 'City',
        REMIT_AMOUNT: 'Amount',
        REMIT_ADDBENEFI: 'Add Remittance Beneficiary',
        TRANSFER_ADDBENEFIT: 'Add Transfer Beneficiary',


        REMIT_NAME: 'Payee Name',
        REMIT_NRCNO: 'NRC No.',
        REMIT_PHONENO: 'Phone No.',
        REMIT_ADDRESS: 'Address',
        REMIT_AMOUNT: 'Amount',
        REMIT_SERVICES: 'Commission',
        REMIT_CHARGES: 'Communication Charges',
        REMIT_TOTAL: 'Total Balance',
        REMIT_PAYEEBRANCH: 'Payee Branch',
        REMIT_BADDRESS: 'Adddress',
        REMIT_TERMSANDCONS: 'I agree to the cannot reserve for confirmed transactions.',
        REMIT_NARRATION: 'Reference',





        //REMITTANCEBENEFICIARY
        REMITBENE_NRC: 'NRC',
        REMITBENE_PHONE: 'Phone No',
        REMITBENE_ADDRESS: 'Address',

        //FEEDBACK
        FEEDBACK_INFO: 'you can send your feedback here.',
        FEEDBACK_NAME: 'Name',
        FEEDBACK_NRC: 'NRC',
        FEEDBACK_MOBILENO: 'Mobile No',
        FEEDBACK_EMAIL: 'Email',
        FEEDBACK_FEEDBACKTYPE: 'Feedback Type',
        FEEDBACK_FEEDBACKTITLE: 'Feedback Title',
        FEEDBACK_CONTINUE: 'Continue',
        FEEDBACK_DESCRIPTION: 'Description',

        ///THIS IS FOR INFORMATION
        HOME_INFO_HEAD: 'Home Page',
        HOME_INFO_BODY: 'Welcome to AGD Bank\'s iBanking System.<br/>Your account numbers are mentioned on the other side, and choose the account number to which bank transactions are desired to be made<br/> for having banking services.',
        PROFILE_INFO_HEAD: 'User Profile',
        PROFILE_INFO_BODY: 'you can view your detail account information here.',
        FEEDBACK_INFO_HEAD: 'Feedback',
        FEEDBACK_INFO_BODY: ' You can make any suggestion regarding to our AGD Bank\'s Internet Banking Service.',
        PASSWORD_INFO_HEAD: 'Password Change',
        PASSWORD_INFO_BODY: 'You can change your password here.Password Length must be at least 5 with at least one digit and one character.',
        SERVICE_INFO_HEAD: 'Services',
        SERVICE_INFO_BODY: 'Choose the services you would like to have regarding your account. ',
        TRANSFER_INFO_HEAD: 'Account Transfer',
        TRANSFER_INFO_BODY: 'This is process by which the money from your account is transferred to another account that you desire to transfer your money to. You have to choose the account number to which you money is desired to transfer to. Afterwards, you have to fill in the amount of money you wish to transfer and your reason for transfer. After clicking the next button, you need to encode the OTP number. If there</br> appers the world, "successfully",</br> your mission is accomplished.</br> SMS will be further sent to your</br> mobile for your information.</br></br>If you want to add a new account</br> to which transfer is desired to be</br>made, click"Add Beneficiary".</br></br>Regarding account transfer service,</br> if the bank account to which transfer</br> is desired to be made happens to be</br> a Hire Purchase Account, account transfer service is not provided.<br/><font class="termsandconditions">Input characters must be english characters.</font>',
        REMITTANCE_INFO_HEAD: 'Remittance',
        REMITTANCE_INFO_BODY: 'This service will enable you to send </br>fast money from your saccount to </br>all  AGD Bank\'s branches.The</br> recipient is not required to open</br>at bank account.Only the name of the recipient is to be filled in an the name </br>of the branch is to be selected. Afterwards, the amount of money you desire to transfer and your reason for transfer are to be entered.Then, click the Next button and enter the OTP code.In the event of wishing to make amendments for the successfully  remitted services, such amendments can be made only by the bank\'s branches concerned. </br></br> If you desire to add a new recipient click “Add Beneficiary” .<br/><font class="termsandconditions">Input characters must be english characters.</font>',
        UTILITY_INFO_HEAD: 'Utility Payment',
        UTILITY_INFO_BODY: 'You can make payment for Meter bill and Phone bills etc from your bank account with perfect trust. You need to select the type of bill first.</br> In case of meter bills, select the divisional region and township.</br> Next, enter the meter box number and particulars. In case of phone bills, enter the phone number for which you desire to pay the bill.</br> Enter 09 for mobile phones and enter 01,02 etc for line phones depending on the city code. Click the Next button and enter the OTP code.<br/><font class="termsandconditions">Input characters must be english characters.</font>',

        TOPUP_INFO_HEAD: 'Top-up Cards',
        TOPUP_INFO_BODY: 'You can purchase the mobile top-up cards like MPT,MEC and Telenor</br> from your bank account just as easily.</br></br>Select the type of operator and the phone line. Then, enter the value of </br>the top-up card, the quantity and particulars.</br></br>Click the Next button and enter the </br>OTP code.<br/><font class="termsandconditions">Input characters must be english characters.</font>',
        STATEMENT_INFO_HEAD: 'Mini Bank statement',
        STATEMENT_INFO_BODY: 'You can check the monthly detailed statement of your bank account.</br></br>Select the range of the date you </br>desire to check.Enter the OTP code and click the Next button.</br></br>Download the statement in the PDF format and save it.',
        HISTORY_INFO_HEAD: 'Transaction History',
        HISTORY_INFO_BODY: 'You can check the money transactions and services transactions processed within a month from your bank account.</br></br>Select the type of services that you desire to check.</br> Then, select the range of the date you desire to check. Then, click the Next button and enter the OTP code.sss',
        CHECKHISTORY_INFO_HEAD: 'Transaction History',
        CHECKHISTORY_INFO_BODY: 'You can check the transaction and services that you have processed within one month.<br/><br/>You have to choose the type of services that you want to check.You have to choose date range by selecting from date and to date that you want to view.<br></br>And then, you need to fill up OTP code after clicking Next button. ',
        TBENEFICIARY_INFO_HEAD: 'Managing Transfer Beneficiary',
        TBENEFICIARY_INFO_BODY: 'To add the new account number you desire to transfer your money to, click"Add Beneficiary".</br>Enter the account number, name, </br>phone number and reason for transfer. </br></br>Then, enter 09 for mobile phones</br> and 01,02 etc for line phones depending</br> on the city code concerned.</br></br>Be careful in entering the account number as the transfer will be made </br>to that account.<br/><font class="termsandconditions">Input characters must be english characters.</font>',
        RBENEFICIARY_INFO_HEAD: 'Managing Remittance Beneficiary',
        RBENEFICIARY_INFO_BODY: 'To add new information regarding the recipient , click "Add Beneficiary".Enter the name, citizenship scrutinization certificate number, phone number and address of the recipient.</br></br>Enter 09 for mobiles and 01,02 etc</br> for line phones depending on the city </br>code concerned.In entering citizenship scrutinization certificate number, the format should be like 12/xxx(N)123456.</br></br>When the message "successfully" appears, you should know that your process is accomplished.<br/><font class="termsandconditions">Input characters must be english characters.</font>',

        ///New itme
        FINISH: 'Finish',
        VOUCHER: 'Get voucher',
        //amy
        LOGIN_WELCOME: 'Welcome User',
        CHECKMYTRANSACTIONS_TITLE: 'Check My Transactions',
        CHECKMYTRANSACTIONS_CHECK: 'You can check your transaction history here.',
        REMITTANCE_TITLE: 'Remittance Service',
        REMITTANCE_SERVICE: 'You can make cash remittance here.',
        PROFILE_INFO: 'you can view your detail account information here.',

        PASSWORDCHANGE_TITLE: 'Password Change',
        PASSWORDCHANGE_CHANGE: 'you can change your password here.',
        PASSWORDCHANGE_RETYPE: 'Retype Password',
        REMITTANCEBENEFICIARY_TITLE: 'Remittance Beneficinary',
        REMITTANCEBENEFICIARY_BENEFICIARY: 'you can remove or add new remittance beneficiary from here.',

        //amp
        LOGIN_PLEASE: '',
        LOGIN_OTP: 'Please use your one time password',
        BALANCEENQUIRY_WELCOME: 'Welcome from AGD IBanking',
        BALANCEENQUIRY_INFORMATION: 'You can see balance information of all your accounts here.',
        PAYMENTOPTION_SERVICES: 'Our Services',
        PAYMENTOPTION_CURRENT: 'Your current selected account number is',
        TOPUP_SERVICE: 'Topup Service',
        TOPUP_PURCHASE: 'You can purchase mobile topup card here.',
        TRANSFER_SERVICE: 'Transfer Service',
        TRANSFER_CASH: 'You can make cash transfer here.',
        UTILITY_SERVICE: 'Utility Service',
        UTILITY_PAYMENT: 'You can make utility payment here.',
        VIEWMINI_VIEW: 'View Ministatement',
        VIEWMINI_CHECK: 'You can check your ministatement information here.',
        VIEWMINI_NOTE: 'Within 1 Month Transactions Only.',
        ADDBENE_NEW: 'You can add new benificiary account here.',
        ADDREMIT_BENE: 'Add Remittance Beneficiary',
        ADDREMIT_NEWBENE: 'You can add new remittance benificiary account here.',
        TRANSFER_RECE: 'Receive Person: ',
        TRANS_AMOUNT: ' Amount data is required and must only number ',
        TOPUP_QUANVALIDATE: ' Topup quantity is required and must only number ',
        REMITTANCE_AMOUNTVALIDATE: ' Amount data is required and must only number ',
        VIEWMINI_TITLE: 'Ministatement',
        VIEWMINI_INFOR: 'You can check your ministatement information here.',
        CHECKTRANS_TOPUPINFOR: 'You can check your Topup information.',
        CHECKTRANS_TRANSFERINFOR: 'You can check your Transfer information.',
        CHECKTRANS_REMITINFOR: 'You can check your Remittance information.',
        REMIT_SUCCESS: 'Your remittance transaction is success.',
        IBANKING_SERVICE: 'Internet Banking Service',

        REMIT_NAME: 'Payee Name',
        REMIT_NRCNO: 'NRC No.',
        REMIT_PHONENO: 'Phone No.',
        REMIT_ADDRESS: 'Address',
        REMIT_AMOUNT: 'Amount',
        REMIT_SERVICE: 'Service Charges',
        REMIT_TOTAL: 'Total Balance',
        REMIT_PAYEEBRANCH: 'Payee Branch',
        REMIT_BADDRESS: 'Adddress',
        REMIT_NARRATION: 'Narration',





        //new item for Index
        ACCOUNT: 'Accounts',
        BENEFICIARY: 'Beneficiaries',
        REMITTANCE_BENEFICIARY: 'Remittance Beneficiary',
        TRANSFER_BENEFICIARY: 'Transfer Beneficiary',
        SERVICES: 'Services',
        FEEDBACK: 'Feedback',
        LANGUAGE: 'Languages',
        INDEXTITLE: 'What do you want?',
        CHANGETO: 'ဘာသာေျပာင္းရန္',

        CHECKPREVIOUS: 'Check previous data',

        //results 
        TRANSFER_SUCCESS: 'Your cash transfer is sucessfully success.',
        TRANSFER_FAIL: 'Sorry cash transfer fail. Error details : ',
        UTILITY_SUCCESS: 'Your utility is successfully.',
        UTILITY_FAIL: 'sorry.',
        REMITTANCE_SUCCESS: 'Your remittance is successfully.',
        REMITTANCE_FAIL: 'sorry.',
        TOPUP_SUCCESS: 'Your topup transaction is successfully!',
        FEEDBACK_SUCCESS: 'Your feedback is successfully send!',
        FEEDBACK_FAIL: 'Sorry your feedback send to server is fail.',
        DIRECTTOPUP_SUCCESS: 'Your direct topup is sucessfully success.',
        DIRECTTOPUP_FAIL: 'Sorry direct topup fail. Error details : ',

        BALENQ_ACCERROR: 'cannot connect to branch server',

        //directtopup
        TITLE_DIRECTTOPUP: 'Direct Topup Service',
        SUBTITLE_DIRECTTOPUP: 'You can fill bill to your phone directly.',
        CHOOSING_OPERATOR: 'Choosing Mobile Operator',
        CHOOSE_OPERATOR: ' Please choose your mobile operator.',
        CHOOSING_AMOUNT: 'Choosing Topup Amount',
        CHOOSE_AMOUNT: 'Please choose your topup amount here.',
        DIRECTTOPUP_INFO_HEAD: 'Direct Topup',
        DIRECTTOPUP_INFO_BODY: '',
        DIRECTTOPUP: 'Direct Topup',
        DIRECTTOPUP_OPERATOR: 'Operator',
        DIRECTTOPUP_TYPE: 'Type',
        DIRECTTOPUP_VALUE: 'Value',
        DIRECTTOPUP_PHONENO: 'Phone No',
        DIRECTTOPUP_REFERENCE: 'Refernece',
        DIRECTTOPUP_TERMSANDCONS: 'I agree that if the entered phone number is wrong,cannot be canceled.',
        CARD_1000: '1000',
        CARD_3000: '3000',
        CARD_5000: '5000',
        CARD_10000: '10000',
        CARD_KS: 'KS.',
        PHONETOPUP: 'Phone Topup',

         //amp:09.04.2015
       DIRECT_TOPUP:'Direct Topup',
       DIRECTTOPUP_SERVICES:'Topup Service',
       DIRECTTOPUP_CURRENT:'Your current selected account number is',
       PHONEBILL_TOPUP:'Phone Bill',

    });

    $translateProvider.translations('mm', {
        LOGIN_TITLE: 'ဝင္ေရာက္ရန္',
        LOGIN_USERNAME: 'အမည္',
        LOGIN_PASSWORD: 'လွ်ဳိ႕ဝွက္ကုဒ္',
        CONTINUE: 'ဆက္သြားရန္',
        SIGIN: 'ဆက္သြားမည္',
        CANCEL: 'မလုပ္ေတာ့ပါ',
        SEARCH: 'ရွာမည္',
        PAYMENT: 'ေပးေဆာင္မည္',

        KYAT: 'က်ပ္',
        ACCOUNTNO: 'ဘဏ္စာရင္းနံပါတ္',

        ENGLISH: 'English',
        MYANMAR: 'ျမန္မာ',
        LOGOUT: 'ထြက္ရန္',
        TRANSFER: 'ဘဏ္စာရင္းလႊဲေျပာင္းမည္',
        UTILITY: 'အခြန္အခမ်ားေပးမည္',
        TOPUP: 'ေငြျဖည့္ကဒ္ဝယ္မည္',
        VIEWMINI: 'စာရင္းရွင္းတမ္း ၾကည့္မည္',
        TRANHISTORY: 'စာရင္းမ်ားရွာမည္',
        PWDCHANGE: 'လွ်ိဳ႕ဝွက္နံပါတ္ ေျပာင္းမည္',
        BENEFICIARY: 'ဘဏ္စာရင္းနံပါတ္',
        PROFILE: 'ကိုယ္ေရးရာဇဝင္',
        REMITTANCE: 'ေငြလႊဲျခင္း ျပဳလုပ္မည္',

        SIDE_TITLE: 'အြန္လိုင္းစနစ္',
        SIDE_FIRSTTEXT: 'Online မွတဆင့္ တယ္လီဖုန္း အခြန္ေငြမ်ား/မီတာအခြန္ေငြမ်ား/Onlineေပၚမွ ေငြေပးေခ်ႏုိင္ေသာ စနစ္တစ္ခုျဖစ္ပါသည္။<br/> အာရွစိမ္းလန္းမႈ ဖြ႔ံၿဖိဳးေရးဘဏ္လီမိတက္၏ Online Payment Account တစ္ခု ဖြင့္လွစ္ထားရံုျဖင့္ <br/>Online မွတဆင့္ ေငြေပးေခ်ႏုိင္ပါၿပီ။',
        SIDE_SECONDTEXT: 'ဖုန္းဘီလ္/မီတာဘီလ္ သြားေဆာင္ရန္ အခ်ိန္မေပးႏုိင္သူမ်ားလည္း ဖုန္း/မီတာ ျဖတ္ခံရျခင္းမွ ကင္းေဝးေစျခင္း။<br/>  Internet အသံုးျပဳႏုိင္သည္႔ မည္သည္႔ေနရာတြင္မဆို ေငြေပးေခ်မႈမ်ားျပဳလုပ္ႏုိင္သျဖင့္<br/>  အခ်ိန္၊လူပင္ပန္းမႈႏွင့္ ကုန္က်စရိတ္မ်ားစြာ သက္သာေစျခင္း။',

        BALENQ_DESP: 'ဘဏ္စာရင္းနံပါတ္ကို ေရြးခ်ယ္ကာ ေငြေပးေခ်မႈမ်ား လုပ္ေဆာင္ႏိုင္ပါသည္။',
        BALENQ_AVAILABLEBAL: 'အသံုးျပဳႏိုင္ေသာ ေငြလက္က်န္ပမာဏ',
        BALENQ_LEDGERBAL: 'ရရွိႏိုင္ေသာ ေငြလက္က်န္ပမာဏ',

        PROFILE_FULLNAME: 'နာမည္',
        PROFILE_EMAIL: 'အီးေမးလ္',

        CARD_INFO: 'ေငြျဖည့္ကဒ္',
        TOPUP_OPERATOR: 'ဖုန္းေအာ္ပေရတာ ကိုေရြးပါ',
        TOPUP_PHONELINE: 'ဖုန္းလိုင္းအမ်ိဳးအစား ကိုေရြးပါ',
        TOPUP_CARDTYPE: 'ေငြျဖည့္ကဒ္အမ်ိဳးအစား ကိုေရြးပါ',
        TOPUP_REFERENCE: 'မွတ္ခ်က္',
        TOPUP_QUANTITY: 'ဝယ္ယူလိုသည့္ ေငြျဖည့္ကဒ္ အေရအတြက္',
        TOPUP_TRANFEES: 'ဝန္ေဆာင္ခ က်သင့္ေငြ',
        TOPUP_NETAMT: 'စုစုေပါင္း က်သင့္ေငြ',
        TOPUP_DISCOUNTAMT: 'ေလွ်ာ့ေစ်း',
        // topup confirm
        TOPUP_COPERATOR: 'ဖုန္းေအာ္ပေရတာ',
        TOPUP_CPHONELINE: 'ဖုန္းလိုင္းအမ်ိဳးအစား',
        TOPUP_CCARDTYPE: 'ေငြျဖည့္ကဒ္အမ်ိဳးအစား',
        TOPUP_CQUANTITY: 'ဝယ္ယူလိုသည့္ ေငြျဖည့္ကဒ္ အေရအတြက္',
        // topup value
        TOPUP_VALUENO: 'ေငြျဖည့္ကဒ္နံပါတ္မွာ ',
        TOPUP_VALUENO1: 'ျဖစ္ျပီး',
        TOPUP_EXPDATE1: 'ျဖစ္ပါသည္။',
        TOPUP_EXPDATE: 'သက္တမ္းကုန္ဆံုးရက္မွာ',

        TRANSFER_TOACCCOUNT: 'ဘဏ္စာရင္းအမွတ္(သို႕) ေရြးပါ',
        TRANSFER_TRANSFERBALANCE: 'ေငြလႊဲရန္ ေငြေၾကးပမာဏ ျဖည့္ပါ',
        TRANSFER_SERVICECHARGES: 'ဝန္ေဆာင္ခ က်သင့္ေငြ',
        TRANSFER_TOTALBALANCE: 'စုစုေပါင္း က်သင့္ေငြ',
        TRANSFER_REFERENCE: 'မွတ္ခ်က္',
        TRANSFER_CONTINUE: 'ေငြလႊဲမည္',
        TRANSFER_BENEFICIARYNAME: 'ေငြလက္ခံမည့္သူ အမည္',
        TRANSFER_ADDBENEFI: 'ေငြလႊဲမည္ ႔ အေကာင္႔ ထည္ ႔သြင္းရန္',
        // transfer confirm
        TRANSFER_CTOACCCOUNT: 'ဘဏ္စာရင္းအမွတ္(သို႕)',
        TRANSFER_CTRANSFERBALANCE: 'ေငြလႊဲရန္ ေငြေၾကးပမာဏ',
         TRANSFER_TERMSANDCONS:'အထက္ေဖာ္ျပပါအခ်က္အလက္မ်ားအား ကိုယ္တိုင္စစ္ေဆးအတည္ျပဳျပီးေၾကာင္းလက္ခံပါသည္။',

        UTILITY_SERVICETYPE: 'ဝန္ေဆာင္မႈ အမ်ိဳးအစားကိုေရြးပါ',
        UTILITY_CITY: 'ၿမိဳ႕ကိုေရြးပါ',
        UTILITY_TOWNSHIP: 'ၿမိဳ႕နယ္ကိုေရြးပါ',
        UTILITY_SERVICENO: 'ဝန္ေဆာင္မႈ နံပါတ္',
        UTILITY_BILLMONTH: 'ဘီ(လ္)ေဆာင္မည့္လ',
        UTILITY_REFERENCE: 'မွတ္ခ်က္',
        // utility confirm
        UTILITY_CSERVICETYPE: 'ဝန္ေဆာင္မႈ အမ်ိဳးအစား',
        UTILITY_CCITY: 'ၿမိဳ႕',
        UTILITY_CTOWNSHIP: 'ၿမိဳ႕နယ္',
        UTILITY_CSERVICENO: 'ဝန္ေဆာင္မႈ နံပါတ္',
        UTILITY_BillAMOUNT: 'ဘီ(လ္)ေဆာင္ရမည့္ ပမာဏ',
        UTILITY_STATUS: 'အေျခအေန',
        UTILITY_BALANCE: 'လက္က်န္ေငြ',
        UTILITY_DUEDATE: 'ေနာက္ဆံုးေပးေဆာင္ရမည့္ေန႕',

        BENE_DESP: 'ေငြလႊဲလိုသည့္ ဘဏ္စာရင္းနံပါတ္မ်ား အသစ္ထည့္ႏိုင္သည္။ ပယ္ဖ်က္ႏိုင္သည္။',
        BENE_ADDNEW: 'အသစ္ထည့္မည္',
        BENE_REMOVE: 'ပယ္ဖ်က္မည္',
        ADDBENE_ADDBENE: 'စာရင္းေျပာင္းလက္ခံမည့္သူအား အသစ္ထည့္ရန္',
        ADDBENE_ACCNO: 'အေကာင့္နံပါတ္',
        ADDBENE_NICKNAME: 'နာမည္',
        ADDBENE_REMARK: 'မွတ္ခ်က္',

        VIEWMINI_FROMDATE: 'ေန႕ရက္(မွ)ကိုေရြးပါ',
        VIEWMINI_TODATE: 'ေန႕ရက္(ထိ)ကိုေရြးပါ',
        VIEWMINI_NOTE: 'သတိျပဳရန္။ (၁)လအတြင္းစာရင္းမ်ားသာ ခြင့္ျပဳသည္။',
        VIEWMINI_DATE: 'ေန႕စြဲ',
        VIEWMINI_CODE: 'ကုဒ္',
        VIEWMINI_DEPOSIT: 'ေငြသြင္း',
        VIEWMINI_WITHDRAW: 'ေငြထုတ္',
        VIEWMINI_TOTALAMT: 'လက္က်န္',
        VIEWMINI_NARRATION: 'မွတ္ခ်က္',

        CHKMYTRAN_TRANTYPE: '၀န္ေဆာင္မႈ အမ်ိဳးအစားကို ေရြးပါ',
        CHKMYTRAN_BILLTYPE: 'ေဘလ္အမ်ိဳးအစား ကိုေရြးပါ',
        CHKMYTRAN_TOACCNO: 'ဘဏ္စာရင္းအမွတ္(သို႕) ကိုေရြးပါ',
        CHKMYTRAN_FROMDATE: 'ေန႕ရက္(မွ)ကိုေရြးပါ',
        CHKMYTRAN_TODATE: 'ေန႕ရက္(ထိ)ကိုေရြးပါ',
        CHKMYTRAN_NOTE: 'သတိျပဳရန္။ (၁)လအတြင္းစာရင္းမ်ားသာ ခြင့္ျပဳသည္။',

        CHKMYTRAN_TRANSFERVIEW_DATE: 'ရက္စြဲ',
        CHKMYTRAN_TRANSFERVIEW_TRANID: 'လုပ္ေဆာင္ခ်က္ အမွတ္စဥ္',
        CHKMYTRAN_TRANSFERVIEW_TRANCODE: 'လုပ္ေဆာင္ခ်က္',
        CHKMYTRAN_TRANSFERVIEW_ACCNO: 'ဘဏ္စာရင္းနံပါတ္',
        CHKMYTRAN_TRANSFERVIEW_AMOUNT: 'ပမာဏ',
        CHKMYTRAN_TRANSFERVIEW_REFERENCE: 'မွတ္ခ်က္',

        CHKMYTRAN_TOPUPVIEW_DATE: 'ရက္စြဲ',
        CHKMYTRAN_TOPUPVIEW_TRANID: 'လုပ္ေဆာင္ခ်က္ အမွတ္စဥ္',
        CHKMYTRAN_TOPUPVIEW_OPERATOR: 'ဖုန္းေအာ္ပေရတာ',
        CHKMYTRAN_TOPUPVIEW_LINE: 'ဖုန္းလိုင္းအမ်ိဳးအစား',
        CHKMYTRAN_TOPUPVIEW_CARD: 'ေငြျဖည့္ကဒ္အမ်ိဳးအစား',
        CHKMYTRAN_TOPUPVIEW_AMOUNT: 'ပမာဏ',
        CHKMYTRAN_TOPUPVIEW_VALUE: 'ေငြျဖည့္ကဒ္နံပါတ္',
        CHKMYTRAN_TOPUPVIEW_EXPDATE: 'သက္တမ္းကုန္ဆံုးရက္',
        CHKMYTRAN_TOPUPVIEW_REFERENCE: 'မွတ္ခ်က္',

        CHKMYTRAN_UTILITYVIEW_DATE: 'ရက္စြဲ',
        CHKMYTRAN_UTILITYVIEW_TRANID: 'လုပ္ေဆာင္ခ်က္ အမွတ္စဥ္',
        CHKMYTRAN_UTILITYVIEW_SERVICENO: '၀န္ေဆာင္မႈ နံပါတ္',
        CHKMYTRAN_UTILITYVIEW_BILLAMOUNT: 'ေဘလ္ေဆာင္ရမည့္ ပမာဏ',
        CHKMYTRAN_UTILITYVIEW_STATUS: 'အေၾကာင္းအရာ',

        CHKMYTRAN_REMITTANCEVIEW_DATE: 'ရက္စြဲ',
        CHKMYTRAN_REMITTANCEVIEW_CREDITUSER: 'ေငြလက္ခံသူ',
        CHKMYTRAN_REMITTANCEVIEW_AMOUNT: 'ပမာဏ',
        CHKMYTRAN_REMITTANCEVIEW_TELEX: 'အခြန္',
        CHKMYTRAN_REMITTANCEVIEW_COMMISSION: 'ေကာ္မရွင္',
        CHKMYTRAN_REMITTANCEVIEW_TOTALAMOUNT: 'စုစုေပါင္း',

        PWDCHANGE_FILLOLDPWD: 'လက္ရွိသံုးေနေသာ လွ်ိဳ႕ဝွက္နံပါတ္ ကိုျဖည့္ပါ',
        PWDCHANGE_FILLNEWPWD: 'ေျပာင္းလဲလိုေသာ လွ်ိဳ႕ဝွက္နံပါတ္ ကိုျဖည့္ပါ',
        PWDCHANGE_CURPWD: 'လက္ရွိသံုးေနေသာ လွ်ိဳ႕ဝွက္နံပါတ္',
        PWDCHANGE_NEWPWD: 'ေျပာင္းလဲလိုေသာ လွ်ိဳ႕ဝွက္နံပါတ္',
        PWDCHANGE_RETYPEPWD: 'ေျပာင္းလဲလိုေသာ လွ်ိဳ႕ဝွက္နံပါတ္',

        //Remittance
        REMIT_NAME: 'ေငြလႊဲမည္ ႔ အမည္ေရြးပါ',
        REMIT_BANKTYPE: 'ဘဏ္အမ်ိဳးအစားကို ေရြးပါ',
        REMIT_SELECTBANK: 'ေငြလႊဲမည္ ႔ ဘဏ္ေရြးပါ',
        REMIT_BANK: 'ေငြလႊဲမည္ ႔ ဘဏ္ခြဲကိုေရြးပါ',
        REMIT_CITY: 'ေငြလႊဲမည္ ႔ ျမိဳ႕ေရြးပါ',
        REMIT_AMOUNT: 'ေငြလႊဲရန္ ေငြေၾကးပမာဏ ျဖည့္ပါ',
        REMIT_NARRATION: 'မွတ္ခ်က္',
        REMIT_ADDBENEFI: 'လႊဲေငြလက္ခံသူ အသစ္ထည့္သြင္းရန္',
        TRANSFER_ADDBENEFIT: 'စာရင္းေျပာင္းလက္ခံသူ အသစ္ထည့္သြင္းရန္',


        REMIT_NAME: 'လႊဲေငြလက္ခံသူအမည္',
        REMIT_NRCNO: 'မွတ္ပုံတင္နံပါတ္',
        REMIT_PHONENO: 'ဖုန္းနံပါတ္',
        REMIT_ADDRESS: 'လိပ္စာ',
        REMIT_AMOUNT: 'လႊဲေငြပမာဏ',
        REMIT_SERVICES: 'ေကာ္မရွင္ခ',
       REMIT_CHARGES: 'ဝန္ေဆာင္ခ',
        REMIT_TOTAL: 'စုစုေပါင္းက်သင့္ေငြ',
        REMIT_PAYEEBRANCH: 'ေပးပုိ့ဘဏ္ခြဲအမည္',
        REMIT_BADDRESS: 'ေပးပုိ႕ဘဏ္ခြဲလိပ္စာ',
        REMIT_NARRATION: 'မွတ္ခ်က္',
        REMIT_TERMSANDCONS: 'ေဖာ္ျပပါေငြလႊဲလုပ္ငန္းအား အတည္ျပဳျပီးပါက ျပန္လည္ပယ္ဖ်က္ခြင့္မရွိသည္ကိုလက္ခံပါသည္။',



        //REMITTANCEBENEFICIARY
        REMITBENE_NRC: 'မွတ္ပုံတင္ နံပါတ္',
        REMITBENE_PHONE: 'ဖုန္းနံပါတ္',
        REMITBENE_ADDRESS: 'လိပ္စာ',

        //FEEDBACK
        FEEDBACK_INFO: 'သင္၏အၾကံေပးခ်က္မ်ားကို ေပးပို႕ႏိုင္ပါသည္။',
        FEEDBACK_NAME: 'နာမည္',
        FEEDBACK_NRC: 'မွတ္ပံုတင္ နံပါတ္',
        FEEDBACK_MOBILENO: 'ဖုန္းနံပါတ္',
        FEEDBACK_EMAIL: 'အီးေမးလ္',
        FEEDBACK_FEEDBACKTYPE: 'အၾကံေပးခ်က္အမ်ိဳးအစား',
        FEEDBACK_FEEDBACKTITLE: 'အၾကံေပးခ်က္္္ ေခါင္းစဥ္',
        FEEDBACK_CONTINUE: 'ပို႕မည္',
        FEEDBACK_DESCRIPTION: 'အႀကံေပးခ်က္ အေၾကာင္းအရာ',

        ///THIS IS FOR INFORMATION
        HOME_INFO_HEAD: 'ပင္မစာမ်က္ႏွာ',
        HOME_INFO_BODY: 'AGD Bank ၏ iBanking စနစ္ကို စတင္အသံုးျပဳေနပါၿပီ။ <br/>လူၾကီးမင္း၏ေငြစာရင္းအမွတ္မ်ားအား တစ္ဖက္တြင္ ေဖၚျပထားျခင္းျဖစ္ၿပီး <br/>ဘဏ္လုပ္ငန္းဆိုင္ရာဝန္ေဆာင္မႈမ်ား <br/>လုုပ္ေဆာင္လုိသည့္ေငြစာရင္းအမွတ္အား<br/>ေရြးခ်ယ္၍ဝန္ေဆာင္မႈမ်ား<br/>စတင္ျပဳလုပ္ႏိုင္မည္ ျဖစ္ပါသည္။',
        SERVICE_INFO_HEAD: '၀န္ေဆာင္မႈမ်ား',
        SERVICE_INFO_BODY: 'လူၾကီးမင္း ၏ေငြစာရင္းအမွတ္ႏွင့္ပတ္သတ္၍ အသံုးျပဳလိုေသာ ဝန္ေဆာင္မွဳမ်ားအား ထပ္မံေရြးခ်ယ္ေပးရမည္ျဖစ္ပါသည္။ ',
        TRANSFER_INFO_HEAD: 'စာရင္းလႊဲေျပာင္းျခင္း',
        TRANSFER_INFO_BODY: ' မိမိဘဏ္စာရင္းမွေငြလႊဲေျပာင္းလိုေသာ <br/>ဘဏ္စာရင္းအမွတ္သို့ စာရင္းေျပာင္းျခင္းလုပ္ငန္းျဖစ္္ပါသည္။ မိမိလႊဲေျပာင္းလိုေသာ စာရင္းအမွတ္အား <br/>ေရြးခ်ယ္ေပးရမည္ျဖစ္ပါသည္။<br/><br/> ထို႔ေနာက္လႊဲေျပာင္းလိုေသာ<br/>ေငြေၾကးပမာဏ၊ အေၾကာင္းအရာမ်ားအား<br/> ျဖည့္စြက္ေပးရမည္ျဖစ္ပါသည္။ ထိုေနာက္ ဆက္ရန္ ကို Click ျပဳလုပ္ပါက တစ္ခါသံုး</br> လွ်ဳိ ႔ဝွက္နံပါတ္(OTP) ကို<br/>ရို္က္သြင္းေပးရမည္ျဖစ္ပါသည္။   "Successfully" ဆိုၿပီး ေဖၚျပပါက လူၾကီးမင္းလုပ္ေဆာင္ေသာဝန္ေဆာင္မွဳ လုပ္ငန္းေအာင္ျမင္ျပီးေျမာက္ျပီ<br/>ျဖစ္ပါသည္။ လူၾကီးမင္း၏ မိုဘိုင္းဖုန္းသို႔ လည္း SMS ေပးပို႔၍ထပ္မံ အသိေပး အေၾကာင္းၾကားမည္ျဖစ္ပါသည္။  <br/><br/>   စာရင္းလႊဲေျပာင္းေပးလိုေသာ စာရင္းအမွတ္ အသစ္အား ထပ္မံျဖည့္စြက္လိုပါက<font color="#15AC8C"> စာရင္းေျပာင္းလက္ခံသူ အသစ္ထည့္သြင္းရန္</font> ကိုျပဳလုပ္ေပးရမည္ျဖစ္ပါသည္။  <br/><br/>စာရင္းလႊဲေျပာင္းျခင္း၀န္ေဆာင္မွဳ<br/>လုပ္ငန္းတြင္ ေငြလႊဲေျပာင္းလိုေသာ<br/>ဘဏ္စာရင္းအမွတ္မွာ အငွားဝယ္<br/>စနစ္ကိုအသံုးျပဳထားပါကစာရင္း<br/>လႊဲေျပာင္း၍မရႏိုင္ပါ။<br/><font class="termsandconditions">အခ်က္အလက္မ်ား ျဖည့္သြင္းရာတြင္<br/>အဂၤလိပ္ဘာသာျဖင့္သာ<br/>ျဖည့္သြင္းေပးရမည္ျဖစ္ပါသည္။</font>',
        FEEDBACK_INFO_HEAD: 'အၾကံေပးရန္',
        FEEDBACK_INFO_BODY: 'AGD Bank ၏ ဘဏ္လုပ္ငန္းဝန္ေဆာင္မွဳ<br/>မ်ားႏွင့္ပတ္သတ္၍ လူၾကီးမင္း၏အၾကံေပးခ်က္မ်ားကို<br/>ေပးပို႔ႏိုင္ပါသည္။',
        PROFILE_INFO_HEAD: 'ကိုယ္ေရးရာဇဝင္',
        PROFILE_INFO_BODY: 'လူႀကီးမင္း၏ ကိုယ္ေရးကိုယ္ရာအခ်က္အလက္မ်ားကို အေသးစိတ္ၾကည့္ရွဳႏိုင္ပါသည္။',
        PASSWORD_INFO_HEAD: 'လွ်ိဳ႕ဝွက္နံပါတ္ေျပာင္းလဲျခင္း',
        PASSWORD_INFO_BODY: 'လူၾကီးမင္း၏ လွ်ိဳ႕ဝွက္နံပါတ္ကို ေျပာင္းလဲႏိုင္ပါသည္။<br/>လ်ိဳ႕ဝွက္နံပါတ္သည္ အနည္းဆံုး(၅)လံုးျဖစ္ရမည္။<br/>ဂဏန္း(၁)လံုး ႏွင့္ အကၡၡရာ(၁)လံုး အနည္းဆံုးပါ၀င္ရမည္<br/>ျဖစ္ပါသည္။',
        REMITTANCE_INFO_HEAD: 'ေငြလႊဲေျပာင္းျခင္း',
        REMITTANCE_INFO_BODY: 'မိမိဘဏ္စာရင္းမွ AGD ဘဏ္ခြဲအားလံုးသို႕<br/>ေငြလႊဲေပးပို႔ျခင္းလုပ္ငန္းကို<br/>လွ်င္ျမန္စြာလုပ္ေဆာင္ႏိုင္ပါမည္။ <br/>မိမိလႊဲပုိ႕ေငြကုိ လက္ခံမည့္သူအေနျဖင့္ ဘဏ္စာရင္း ဖြင့္လွစ္ရန္မလိုအပ္ဘဲ လႊဲေငြေပးပို႔လိုေသာသူ၏ အမည္ ႏွင့္ <br/>လႊဲပို႕ေပးလုိေသာဘဏ္ခြဲအမည္အား<br/> ျဖည့္စြက္ေပးရန္လိုအပ္မည္ျဖစ္ပါသည္။<br/><br/>ထို့ေနာက္လႊဲေျပာင္းလိုေသာ<br/> ေငြေၾကးပမာဏ၊ အေၾကာင္းအရာမ်ားအား ျဖည့္စြက္<br/>ေပးရမည္ျဖစ္ပါသည္။ ထို႔ေနာက္ ဆက္ရန္ ကို ႏွိပ္၍ တစ္ခါသံုး လွ်ဳိ ႔ဝွက္နံပါတ္(OTP) ကိုရို္က္သြင္းေပးရမည္ျဖစ္ပါသည္။<br/><br/>ေအာင္ျမင္စြာေငြလႊဲေပးပို႔ၿပီး သည့္ လုပ္ငန္းမ်ားအတြက္ အမွားျပင္ဆင္ျခင္းဆိုင္ရာလုပ္ငန္းမ်ား<br/>ျပဳလုပ္လိုပါက သက္ဆိုင္ရာဘဏ္ခြဲ <br/>မ်ားတြင္သာ ျပဳလုပ္ေပးရမည္ျဖစ္ပါသည္။<br/><br/>ေငြလႊဲေပးလိုေသာ သူအသစ္အား ထပ္မံျဖည့္စြက္လိုပါက <font color="#15AC8C"> လႊဲေငြလက္ခံသူ အသစ္ထည့္သြင္းရန္</font> ကိုျပဳလုပ္ေပးရမည္ျဖစ္ပါသည္။<br/><font class="termsandconditions">အခ်က္အလက္မ်ား ျဖည့္သြင္းရာတြင္<br/>အဂၤလိပ္ဘာသာျဖင့္သာ<br/>ျဖည့္သြင္းေပးရမည္ျဖစ္ပါသည္။</font>',
        UTILITY_INFO_HEAD: 'အခြန္အခမ်ားေပးေဆာင္ျခင္း',
        UTILITY_INFO_BODY: 'Meter Bill, Phone Bill အစရွိေသာ <br/>ဘီ(လ္)မ်ားကိုမိမိဘဏ္စာရင္းမွ စိတ္ခ်ယံုၾကည္စြာေပးေဆာင္ႏိုင္မည္<br/> ျဖစ္ပါသည္။ဘီ(လ္) ေပးေဆာင္ျခင္း<br/>လုပ္ငန္းမ်ားအတြက္မိမိေပးေဆာင္<br/>လိုေသာဘီ(လ္)အမ်ိဳးအစားအား<br/> ေရြးခ်ယ္ေပးရမည္ျဖစ္ပါသည္။<br/>Meterဘီ(လ္)ေပးေဆာင္လုိပါက<br/>မိမိေပးေဆာင္လိုေသာ တိုင္းေဒသၾကီး ႏွင့္ ျမိဳ႕နယ္ အား ေရြးခ်ယ္ေပးရမည္ျဖစ္ပါသည္။<br/><br/>ထိုေနာက္ဘီ(လ္)ေပးေဆာင္လုိေသာ<br/> မီတာနံပါတ္ႏွင့္အေၾကာင္းအရာမ်ားအား<br/> ျဖည့္စြက္ေပးရမည္ျဖစ္ပါသည္။<br/>Phone ဘီ(လ္)ေပးေဆာင္လိုပါက မိမိ(ဘီ)လ္ေပးေဆာင္လိုေသာ ဖုန္းနံပါတ္ အားျဖည့္စြက္ေပးရမည္ျဖစ္ပါသည္။ ဖုန္းနံပါတ္မ်ားအား ရိုက္သြင္းရာတြင္   နမူနာပံုစံတြင္ ေဖၚျပထားသကဲ့သုိ႔ မိုဘိုင္းဖုန္းျဖစ္ပါက \'09\' ျဖင့္လည္းေကာင္း လိုင္းဖုန္းမ်ားျဖစ္ပါက \'01\', \'02\' စသည့္<br/> ျမိဳ ႔ ကုဒ္နံပါတ္ မ်ားျဖင့္ရိုက္သြင္း<br/>ေပးရမည္ျဖစ္ပါသည္။ ထို႔ေနာက္<br/>ဆက္ရန္ ကို Click ျပဳလုပ္ပါက <br/>တစ္ခါသံုးလွ်ဳိ ႔ဝွက္နံပါတ္(OTP) ကိုရို္က္သြင္းေပးရမည္ျဖစ္ပါသည္။<br/><font class="termsandconditions">အခ်က္အလက္မ်ား ျဖည့္သြင္းရာတြင္<br/>အဂၤလိပ္ဘာသာျဖင့္သာ<br/>ျဖည့္သြင္းေပးရမည္ျဖစ္ပါသည္။</font>',
        TOPUP_INFO_HEAD: 'ေငြျဖည့္ကဒ္ဝယ္ယူျခင္း',
        TOPUP_INFO_BODY: 'MPT, MEC , Telenor အစရွိသည့္<br/>ေငြျဖည့္ကဒ္မ်ားကိုမိမိဘဏ္စာရင္းမွ<br/>အလြယ္တကူဝယ္ယူႏိုင္ပါသည္။မိမိ<br/>ဝယ္ယူလိုေသာ ေငြျဖည့္ကဒ္၏ ဖုန္း Operator အမ်ိဳးအစားႏွင့္<br/>လိုင္းအမ်ိဳးအစားအားေရြးခ်ယ္<br/>ေပးရမည္ျဖစ္ပါသည္။<br/><br/>ထို႕ေနာက္ေငြျဖည့္ကဒ္တန္ဖိုး<br/>အမ်ိဳးအစား၊ဝယ္ယူလိုေသာကဒ္<br/> အေရအတြက္ႏွင့္အေၾကာင္းအရာ<br/>အား  ျဖည့္စြက္ေပးရမည္ျဖစ္ပါသည္။ ထို႔ေနာက္ ဆက္ရန္ ကို Click  ျပဳလုပ္ပါက တစ္ခါသံုး လွ်ဳိ ႔ဝွက္နံပါတ္(OTP) ကိုရို္က္သြင္းေပးရမည္ျဖစ္ပါသည္။<br/><font class="termsandconditions">အခ်က္အလက္မ်ား ျဖည့္သြင္းရာတြင္<br/>အဂၤလိပ္ဘာသာျဖင့္သာ<br/>ျဖည့္သြင္းေပးရမည္ျဖစ္ပါသည္။</font>',
        STATEMENT_INFO_HEAD: 'စာရင္းရွင္းတမ္းၾကည့္ျခင္း',
        STATEMENT_INFO_BODY: 'မိမိဘဏ္စာရင္းအမွတ္မွတစ္လအတြင္း<br/>ျပဳလုပ္ထားေသာစာရင္းရွင္းတမ္းမ်ားကို<br/>အေသးစိတ္ၾကည့္ရွဳႏိုင္ပါသည္။<br/>မိမိၾကည့္ရွဳလိုေသာ ေန႕ရက္ မွ ၾကည့္ရွဳလိုေသာ ေန႔ရက္ထိ အား ေရြးခ်ယ္ေပးရမည္ျဖစ္ပါသည္။<br/>ထို႔ေနာက္ တစ္ခါသံုး လွ်ဳိ ႔ဝွက္နံပါတ္<br/>(OTP) ကိုရို္က္သြင္းေပးျပီး ဆက္ရန္ ကို ႏွိပ္ေပးရမည္ျဖစ္ပါသည္။ <br/><br/>စာရင္းရွင္းတမ္းအား PDF  ျဖင့္ ေဒါင္းလုပ္ျပဳလုပ္၍ သိမ္းဆည္းႏိုင္မည္ျဖစ္ပါသည္။',
        HISTORY_INFO_HEAD: 'စာရင္းမ်ားရွာျခင္း',
        HISTORY_INFO_BODY: 'မိမိဘဏ္စာရင္းအမွတ္မွတစ္လအတြင္း<br/>ျပဳလုုပ္ထားေသာ ေငြစာရင္းဆိုင္ရာ<br/>လုပ္ေဆာင္ခ်က္မ်ား၊ ျပဳလုပ္ထားေသာ<br/>၀န္ေဆာင္မွဳလုပ္ငန္းမ်ားကို ၾကည့္ရွဳႏိုင္မည္ျဖစ္ပါသည္။<br/>မိမိၾကည့္ရွဳလိုေသာ၀န္ေဆာင္မွဳ<br/>လုပ္ငန္းအမ်ိဳးအစားအားေရြးခ်ယ္<br/>ေပးရမည္ျဖစ္ပါသည္။ မိမိၾကည့္ရႈလိုေသာ ေန႕ရက္ မွ ၾကည့္ရွဳလိုေသာ ေန႔ရက္ထိ အား ေရြးခ်ယ္ေပးရမည္ျဖစ္ပါသည္။<br/>ထို႔ေနာက္ ဆက္ရန္ ကို Click  ျပဳလုပ္ပါက တစ္ခါသံုး လွ်ဳိ ႔ဝွက္နံပါတ္(OTP) ကိုရို္က္သြင္းေပးရမည္ျဖစ္ပါသည္။',
        CHECKHISTORY_INFO_HEAD: 'စာရင္းမ်ားရွာျခင္း',
        CHECKHISTORY_INFO_BODY: 'မိမိဘဏ္စာရင္းအမွတ္မွတစ္လအတြင္း<br/>ျပဳလုုပ္ထားေသာ ေငြစာရင္းဆိုင္ရာ<br/>လုပ္ေဆာင္ခ်က္မ်ား၊ ျပဳလုပ္ထားေသာ<br/>၀န္ေဆာင္မွဳလုပ္ငန္းမ်ားကို ၾကည့္ရွဳႏိုင္မည္ျဖစ္ပါသည္။<br/>မိမိၾကည့္ရွဳလိုေသာ၀န္ေဆာင္မွဳ<br/>လုပ္ငန္းအမ်ိဳးအစားအားေရြးခ်ယ္<br/>ေပးရမည္ျဖစ္ပါသည္။ မိမိၾကည့္ရႈလိုေသာ ေန႕ရက္ မွ ၾကည့္ရွဳလိုေသာ ေန႔ရက္ထိ အား ေရြးခ်ယ္ေပးရမည္ျဖစ္ပါသည္။<br/>ထို႔ေနာက္ ဆက္ရန္ ကို Click  ျပဳလုပ္ပါက တစ္ခါသံုး လွ်ဳိ ႔ဝွက္နံပါတ္(OTP) ကိုရို္က္သြင္းေပးရမည္ျဖစ္ပါသည္။',
        TBENEFICIARY_INFO_HEAD: 'စာရင္းလႊဲေျပာင္းလိုသူ၏ အခ်က္အလက္မ်ားအားစီမံခန့္ခြဲျခင္း',
        TBENEFICIARY_INFO_BODY: 'မိမိစာရင္းလႊဲေျပာင္းေပးလိုေသာ<br/>စာရင္းအမွတ္ ၊ နာမည္ ၊ ဖုန္းနံပါတ္ ႏွင့္ စာရင္းလႊဲလိုေသာ အေၾကာင္းအရာ တို႔အားျဖည့္စြက္ေပးရမည္ျဖစ္ပါသည္။<br/><br/>နမူနာ ပံုစံတြင္ ေဖၚျပထားသကဲ့သုိ႔.. မိုဘိုင္းဖုန္းျဖစ္ပါက \'09\' ျဖင့္လည္းေကာင္း လိုင္းဖုန္းမ်ားျဖစ္ပါက \'01\', \'02\' စသည့္<br/> ျမိဳ ႔ ကုဒ္နံပါတ္ မ်ားျဖင့္ ရိုက္သြင္းေပးရမည္ျဖစ္ပါသည္။<br/><br/> ေရးသြင္းလိုက္ေသာ စာရင္းအမွတ္အား ေငြစာရင္း လႊဲေျပာင္းေပးမႈ ျပဳလုပ္မည္ျဖစ္ပါသျဖင့္ <br/>ေသခ်ာစြာ စစ္ေဆးၿပီးရိုက္သြင္းေပးရန္ အထူးသတိေပးလိုပါသည္။<br/><font class="termsandconditions">အခ်က္အလက္မ်ား ျဖည့္သြင္းရာတြင္<br/>အဂၤလိပ္ဘာသာျဖင့္သာ<br/>ျဖည့္သြင္းေပးရမည္ျဖစ္ပါသည္။</font>',
        RBENEFICIARY_INFO_HEAD: 'ေငြလႊဲေျပာင္းလိုသူ၏ အခ်က္အလက္မ်ားအားစီမံခန့္ခြဲျခင္း',
        RBENEFICIARY_INFO_BODY: 'မိမိေငြလႊဲေပးလိုသူ နာမည္ ၊ မွတ္ပံုတင္အမွတ္ ၊ ဖုန္းနံပါတ္ ႏွင့္<br/>ေနရပ္လိပ္စာတို႔အားျဖည့္စြက္<br/>ေပးရမည္ျဖစ္ပါသည္။<br/><br/>နမူနာ ပံုစံတြင္ ေဖၚျပထားသကဲ့သုိ႔.. မိုဘိုင္းဖုန္းျဖစ္ပါက \'09\' ျဖင့္လည္းေကာင္း လိုင္းဖုန္းမ်ားျဖစ္ပါက \'01\', \'02\' စသည့္<br/> ျမိဳ ႔ကုဒ္နံပါတ္ မ်ားျဖင့္ ရိုက္သြင္းေပး၍ လည္းေကာင္း၊    မွတ္ပုံတင္နံပါတ္မ်ား ရိုက္သြင္းရာတြင္ 12/xxx(N)123456 ကဲ့သို႔လည္းေကာင္းရိုက္သြင္းရန္<br/>လိုအပ္မည္ျဖစ္ပါသည္။<br/><br/> ေရးသြင္းလိုက္ေသာ အမည္၊မွတ္ပုံတင္ နံပါတ္အား ေငြလႊဲေျပာင္း<br/>ေပးမွဳ  ျပဳလုပ္မွာျဖစ္ပါသျဖင့္ ေသခ်ာစြာ စစ္ေဆးၿပီးရိုက္သြင္းေပးရန္ အထူးသတိေပးလိုပါသည္။<br/><font class="termsandconditions">အခ်က္အလက္မ်ား ျဖည့္သြင္းရာတြင္<br/>အဂၤလိပ္ဘာသာျဖင့္သာ<br/>ျဖည့္သြင္းေပးရမည္ျဖစ္ပါသည္။</font>',
        ///New itme
        LOGIN_WELCOME: 'မဂၤလာပါ',
        FINISH: 'ျပီးပါျပီ',
        VOUCHER: 'ေျပစာထုတ္ယူရန္',
        //amy
        CHECKMYTRANSACTIONS_TITLE: 'စာရင္းမ်ားရွာျခင္း',
        CHECKMYTRANSACTIONS_CHECK: 'လူၾကီးမင္းျပဳလုပ္ထားေသာ ေငြစာရင္းဆိုင္ရာလုပ္ေဆာင္ခ်က္မ်ား ႏွင့္ ဝန္ေဆာင္မွဳလုပ္ငန္းမ်ားကို ၾကည့္ရွဳႏိုင္ပါသည္။',
        REMITTANCE_TITLE: 'ေငြလႊဲေျပာင္းျခင္း၀န္ေဆာင္မွဳ',
        REMITTANCE_SERVICE: 'ေငြလႊဲေပးပို႕ျခင္းလုပ္ငန္းကို လုပ္ေဆာင္ႏိုင္ပါသည္။',
        PROFILE_INFO: 'လူၾကီးမင္း၏  ကိုယ္ေရးကိုယ္ရာအခ်က္အလက္မ်ားကို အေသးစိတ္ၾကည့္ရွဳႏိုင္ပါသည္။',
        PASSWORDCHANGE_TITLE: 'လွ်ိဳ႕ဝွက္နံပါတ္ေျပာင္းလဲျခင္း',
        PASSWORDCHANGE_CHANGE: 'လူၾကီးမင္း၏ လွ်ိဳ႕ဝွက္နံပါတ္ကို ေျပာင္းလဲႏိုင္ပါသည္။',
        PASSWORDCHANGE_RETYPE: 'ေျပာင္းလဲလိုေသာ လွ်ိဳ႕ဝွက္နံပါတ္ ကိုထပ္မံျဖည့္ပါ။',
        REMITTANCEBENEFICIARY_TITLE: 'လႊဲေငြလက္ခံမည့္သူစာရင္း',
        REMITTANCEBENEFICIARY_BENEFICIARY: 'ေငြလႊဲလိုသည့္ ဘဏ္စာရင္းနံပါတ္မ်ား အသစ္ထည့္ႏိုင္သည္။ ပယ္ဖ်က္ႏိုင္သည္။',
        BENEFICIARY_TITLE: 'စာရင္းေျပာင္းလက္ခံမည့္သူစာရင္း',

        //apk
        BENEFICIARYEDIT_TITLE: 'အခ်က္အလက္မ်ားျပင္ဆင္ရန္',
        BENEEDIT_DESP: 'လႊဲေငြလက္ခံမည့္သူ၏ အခ်က္အလက္မ်ားကိုျပင္ဆင္ႏိုင္ပါသည္။',

        //amp
        LOGIN_WELCOME: 'မဂၤလာပါ',
        LOGIN_PLEASE: '',
        LOGIN_OTP: 'လွ်ဳိ႕ဝွက္နံပါတ္(OTP) ကုိျဖည္႕သြင္းေပးပါ',
        BALANCEENQUIRY_WELCOME: 'AGD Bank ၏ အင္တာနက္ Banking ဝန္ေဆာင္မွဳ မွ ႀကိဳဆုိပါသည္။',
        BALANCEENQUIRY_INFORMATION: 'လူႀကီးမင္းစာရင္း ေရးသြင္းထားသည္႕ စာရင္းအမွတ္မ်ား၏ ေငြလက္က်န္ပမာဏမ်ားကုိၾကည္႕ရွဳနဳိင္ပါသည္။',
        PAYMENTOPTION_SERVICES: 'ဝန္ေဆာင္မွဳမ်ား',
        PAYMENTOPTION_CURRENT: 'မိမိစာရင္းအမွတ္ႏွင့္ပတ္သက္ေသာ ဝန္ေဆာင္မွဳမ်ားျဖစ္ပါသည္။',
        TOPUP_SERVICE: 'ေငြျဖည္႕ကဒ္ဝယ္ယူျခင္း ဝန္ေဆာင္မွဳ',
        TOPUP_PURCHASE: 'မိမိဘဏ္စာရင္းမွ ဖုန္းေငြျဖည္႕ကဒ္မ်ားကုိ ဝယ္ယူနဳိင္ပါသည္',
        TRANSFER_SERVICE: 'စာရင္းလႊဲေျပာင္းျခင္းဝန္ေဆာင္မွဳ',
        TRANSFER_CASH: 'မိမိဘဏ္စာရင္းမွေငြလႊဲေျပာင္းလိုေသာ ဘဏ္စာရင္းအမွတ္သို့ စာရင္းေျပာင္းနဳိင္ပါသည္။',
        UTILITY_SERVICE: 'အခြန္အခမ်ားေပးေဆာင္ျခင္းဝန္ေဆာင္မွဳ',
        UTILITY_PAYMENT: 'လူၾကီးမင္း၏ စာရင္းအမွတ္မွ ဘီ(လ္) ေပးေဆာင္ျခင္း လုပ္ငန္းမ်ားကုိ လုပ္ေဆာင္နဳိင္ပါသည္။',
        VIEWMINI_VIEW: 'စာရင္းရွင္းတမ္းမ်ားၾကည့္ရန္',
        VIEWMINI_CHECK: ' မိမိဘဏ္စာရင္းမွ စာရင္းရွင္းတမ္းမ်ားကုိ ၾကည္႕ရွဳစစ္ေဆးနဳိင္ပါသည္။',
        VIEWMINI_NOTE: 'တစ္လအတြင္းျပဳလုပ္ထားေသာ စာရင္းရွင္းတမ္းမ်ားကုိသာ ၾကည္႕ရွဳနိဳင္ပါသည္။',
        ADDBENE_NEW: 'စာရင္းလႊဲေျပာင္းလက္ခံမည့္သူအား အသစ္ထည့္သြင္းနဳိင္ပါသည္',
        ADDREMIT_BENE: 'လႊဲေငြလက္ခံမည့္သူအား အသစ္ထည့္ရန္',
        ADDREMIT_NEWBENE: 'လႊဲေငြလက္ခံမည္႕သူအား အသစ္ထည့္သြင္းနဳိင္ပါသည္',
        TRANSFER_RECE: 'လက္ခံမည့္သူ ',
        TRANS_AMOUNT: '  ေငြလႊဲမည့္ ေငြေၾကးပမာဏကုိ ကိန္းဂဏန္းမ်ားျဖင္႕သာေရးသြင္းရမည္ ',
        TOPUP_QUANVALIDATE: ' ဝယ္ယူမည့္ ေငြျဖည္ ႔ကဒ္ပမာဏကုိ ကိန္းဂဏန္းမ်ားျဖင္႕သာေရးသြင္းရမည္ ',
        REMITTANCE_AMOUNTVALIDATE: ' ေငြလႊဲမည့္ ေငြေၾကးပမာဏကုိ ကိန္းဂဏန္းမ်ားျဖင္႕သာေရးသြင္းရမည္ ',
        VIEWMINI_TITLE: 'စာရင္းရွင္းတမ္းမ်ား',
        VIEWMINI_INFOR: 'လူႀကီးမင္း၏ တစ္လအတြင္းလုပ္ေဆာင္ခ်က္ခ်က္မ်ားကုိ ၾကည့္ရွဳနဳိင္ပါသည္',
        CHECKTRANS_TOPUPINFOR: 'ေငြျဖည္႔ကဒ္ႏွင္႔ပတ္သက္ေသာ လုပ္ေဆာင္ခ်က္မ်ားကုိ ၾကည့္ရွဳနဳိင္ပါသည္',
        CHECKTRANS_TRANSFERINFOR: 'လူႀကီးမင္း၏ စာရင္းအမွတ္မွ စာရင္းလႊဲေျပာင္းျခင္း လုပ္ေဆာင္ခ်က္မ်ားကုိ ၾကည့္ရွဳနဳိင္ပါသည္',
        CHECKTRANS_REMITINFOR: ' လူႀကီးမင္း၏ လႊဲေငြေပးပုိ႕ျခင္း လုပ္ေဆာင္ခ်က္မ်ားကုိ ၾကည့္ရွဳနဳိင္ပါသည္',
        REMIT_SUCCESS: 'လူၾကီးမင္းလုပ္ေဆာင္ေသာဝန္ေဆာင္မွဳ လုပ္ငန္းေအာင္ျမင္ျပီးေျမာက္ျပီျဖစ္ပါသည္။',
        IBANKING_SERVICE: 'အင္တာနက္ဘဏ္လုပ္ငန္း ဝန္ေဆာင္မွဳ',


        REMIT_NAME: 'လႊဲေငြလက္ခံသူအမည္',
        REMIT_NRCNO: 'မွတ္ပုံတင္နံပါတ္',
        REMIT_PHONENO: 'ဖုန္းနံပါတ္',
        REMIT_ADDRESS: 'လိပ္စာ',
        REMIT_AMOUNT: 'လႊဲေငြပမာဏ',
        REMIT_SERVICE: 'ဝန္ေဆာင္ခက်သင့္ေငြ',
        REMIT_TOTAL: 'စုစုေပါင္းက်သင့္ေငြ',
        REMIT_PAYEEBRANCH: 'ေပးပုိ့ဘဏ္ခြဲအမည္',
        REMIT_BADDRESS: 'ေပးပုိ႕ဘဏ္ခြဲလိပ္စာ',
        REMIT_NARRATION: 'မွတ္ခ်က္',






        //new item for Index
        ACCOUNT: 'ဘဏ္စာရင္းအမွတ္မ်ား',
        BENEFICIARY: 'ေငြလႊဲလက္ခံမည့္သူစာရင္း',
        REMITTANCE_BENEFICIARY: 'လႊဲေငြလက္ခံမည့္သူ',
        TRANSFER_BENEFICIARY: 'စာရင္းေျပာင္းလက္ခံမည့္သူ',
        SERVICES: 'ဝန္ေဆာင္မွဳမ်ား',
        FEEDBACK: 'အၾကံေပးရန္',
        LANGUAGE: 'ဘာသာစကား',
        INDEXTITLE: 'အသံုးျပဳလိုသည့္ဝန္ေဆာင္မွဳအားေရြးခ်ယ္ရန္',
        CHANGETO: 'Change to',

        CHECKPREVIOUS: 'ယခင္လုပ္ေဆာင္မွဳမ်ားၾကည့္ရန္',

        //results 
        TRANSFER_SUCCESS: 'သင္ေငြလႊဲျခင္း လုပ္ငန္းေအာင္ျမင္စြာ ျပီးဆံုးသြားျပီျဖစ္ပါသည္။',
        TRANSFER_FAIL: 'ေငြလႊဲျခင္း လုပ္ငန္း ျပီးဆံုးျခင္းမရွိပါ။ Error details :',
        UTILITY_SUCCESS: 'သင္ ဘီ(လ္)ေဆာင္ျခင္း ေအာင္ျမင္စြာ ျပီးဆုံးပါျပီျဖစ္ပါသည္။',
        REMITTANCE_SUCCESS: 'သင္ ေငြလႊဲျခင္း ေအာင္ျမင္စြာ ျပီးဆုံးပါျပီျဖစ္ပါသည္။',
        TOPUP_SUCCESS: 'သင္ ဖုန္းေငြျဖည္ ႔ျခင္း ေအာင္ျမင္စြာ ျပီးဆုံးပါျပီျဖစ္ပါသည္။',
        FEEDBACK_SUCCESS: 'သင့္အၾကံေပးခ်က္ ေအာင္ျမင္စြာ ပို႕ေဆာင္ၿပီးသြားျပီျဖစ္ပါသည္။',
        FEEDBACK_FAIL: 'သင့္အၾကံေပးခ်က္ ပို႕ေဆာင္မႈ ၿပီးဆံုးျခင္းမရွိပါ။',
        DIRECTTOPUP_SUCCESS: 'Your direct topup is sucessfully success.',
        DIRECTTOPUP_FAIL: 'Sorry direct topup fail. Error details : ',

        BALENQ_ACCERROR: 'cannot connect to branch server ',

        //directtopup
        TITLE_DIRECTTOPUP: 'ဖုန္းေငြျဖည့္ျခင္း ဝန္ေဆာင္မွဳ',
        SUBTITLE_DIRECTTOPUP: 'မိမိဘဏ္စာရင္းမွ ဖုန္းေငြျဖည့္ႏိုင္ပါသည္။',
        CHOOSING_OPERATOR: 'ဖုန္းေအာ္ပေရတာ ေရြးခ်ယ္ျခင္း',
        CHOOSE_OPERATOR: 'လူၾကီးမင္း၏ ဖုန္းေအာ္ပေရတာ အမ်ိဳးအစားကိုေရြးခ်ယ္ပါ။',
        CHOOSING_AMOUNT: 'ေငြျဖည့္ကဒ္ တန္ဖိုးေရြးခ်ယ္ျခင္း',
        CHOOSE_AMOUNT: 'လူၾကီးမင္းဝယ္ယူလိုေသာ ေငြျဖည့္ကဒ္တန္ဖိုးကိုေရြးခ်ယ္ပါ။',
        DIRECTTOPUP_INFO_HEAD: 'ဖုန္းေငြျဖည့္သြင္းျခင္း',
        DIRECTTOPUP_INFO_BODY: 'MPT,MEC,Telenor အစရွိသည္႕မုိဘုိင္းဖုန္းမ်ားသုိ႕မိမိဘဏ္</br>  စာရင္းမွ အလြယ္တကူတုိက္ရုိက္ေငြျဖည္႕</br>သြင္းနဳိင္မည္ျဖစ္ပါသည္။မိမိျဖည္႕သြင္းလုိ</br>ေသာမုိဘုိင္းဖုန္းေအာ္ပေရတာအမ်ဳိးအစားႏွင္႕</br>လုိင္းအမ်ဳိးအစားအားေရြးခ်ယ္ေပးရမည္</br>ျဖစ္ပါသည္။ထုိ႕ေနာက္ေငြျဖည္႕လုိေသာ</br>တန္ဖုိးေရြးခ်ယ္ေပးရမည္ျဖစ္ပါသည္။ ဖုန္းနံပါတ္မ်ားရုိက္သြင္းရာတြင္ နမူနာပုံစံတြင္ေဖာ္ျပထားသကဲသုိ႕</br>မုိဘုိင္းဖုန္းျဖစ္ပါက\'09\'အစျဖင္႕ရုိက္သြင္း</br>ေပးရမည္။ ထုိ႕ေနာက္ဆက္ရန္ကုိ Click ျပဳလုပ္ပါက လုပ္ငန္းစဥ္အတည္ျပဳခ်က္ျပဳလုပ္နဳိင္ရန္ အေသးစိတ္အခ်က္အလက္အားေဖာ္ျပေပးမွာ</br> ျဖစ္ၿပီးမွန္ကန္ပါက တစ္ခါသုံးလွ်ဳိ႕ဝွက္နံပါတ္ (OTP) ကုိရုိက္သြင္းေပးကာ Confirm ခလုပ္အားႏွိပ္၍ အတည္ျပဳေပးရမည္ျဖစ္ပါသည္။ </br> အထူးသျပဳရန္မွာ မိမိျဖည့္သြင္းလိုေသာ ဖုန္းနံပါတ္အား မွန္ကန္စြာေသခ်ာရိုက္သြင္းရမည္ျဖစ္ၿပီး၊ မွားယြင္းမႈျဖစ္ပါက ျပန္လည္ ျပင္ဆင္၍ ရမည္မဟုတ္ေပ  ',

        DIRECTTOPUP: 'ဖုန္းေငြျဖည့္သြင္းျခင္း',
        DIRECTTOPUP_PHONENO: 'ဖုန္းနံပါတ္',
        DIRECTTOPUP_OPERATOR: 'Operator',
        DIRECTTOPUP_TYPE: 'Type',
        DIRECTTOPUP_VALUE: 'Value',
        DIRECTTOPUP_REFERENCE: 'မွတ္ခ်က္',
        DIRECTTOPUP_TERMSANDCONS: 'ျဖည့္သြင္းထားေသာဖုန္းနံပါတ္မွားယြင္းမႈျဖစ္ပါက ျပန္လည္ျပင္ဆင္ခြင့္မရွိသည္ကိုလက္ခံပါသည္။ ',
        CARD_1000: '၁၀၀၀',
        CARD_3000: '၃၀၀၀',
        CARD_5000: '၅၀၀၀',
        CARD_10000: '၁၀၀၀၀',
        CARD_KS: 'က်ပ္.',
        PHONETOPUP: 'ဖုန္းေငြျဖည့္ျခင္း',

       //amp:09.04.2015
       DIRECT_TOPUP:'တုိက္ရုိက္ဖုန္းေငြျဖည့္မည္',
       DIRECTTOPUP_SERVICES:'ဖုန္းေငြျဖည့္ျခင္းဝန္ေဆာင္မွဳ',
       DIRECTTOPUP_CURRENT:'မိမိဘဏ္စာရင္းမွ အလြယ္တကူ တိုက္ရိုက္ ဘီလ္ျဖည့္သြင္းႏိုင္မည္ ျဖစ္ပါသည္။',
       PHONEBILL_TOPUP:'ဖုန္းဘီ(လ္)ေဆာင္မည္',
    });

    $translateProvider.preferredLanguage('mm');
});




